app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/saferydb
      username: saferydb
      password: 'saferydbpass'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always